//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KindergartenJoy
{
    using System;
    using System.Collections.Generic;
    
    public partial class evidencija
    {
        public int evidencija_id { get; set; }
        public int grupa_id { get; set; }
        public System.DateTime vrijeme_dolaska { get; set; }
        public Nullable<System.DateTime> vrijeme_odlaska { get; set; }
        public Nullable<int> dijete_id { get; set; }
    
        public virtual grupa grupa { get; set; }
        public virtual dijete dijete { get; set; }
    }
}
