//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KindergartenJoy
{
    using System;
    using System.Collections.Generic;
    
    public partial class korisnik
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public korisnik()
        {
            this.aktivnost = new HashSet<aktivnost>();
            this.biljeska = new HashSet<biljeska>();
            this.dnevnik = new HashSet<dnevnik>();
            this.obavijest = new HashSet<obavijest>();
            this.upis = new HashSet<upis>();
        }
    
        public int korisnik_id { get; set; }
        public int aktivnost_id { get; set; }
        public int tip_korisnik_id { get; set; }
        public string korisnicko_ime { get; set; }
        public string ime { get; set; }
        public string prezime { get; set; }
        public string lozinka { get; set; }
        public string lozinka_sha256 { get; set; }
        public string email { get; set; }
        public string telefon { get; set; }
        public string status { get; set; }
        public string pretplata { get; set; }
        public Nullable<int> grupa_id { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<aktivnost> aktivnost { get; set; }
        public virtual aktivnost aktivnost1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<biljeska> biljeska { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<dnevnik> dnevnik { get; set; }
        public virtual tip_korisnik tip_korisnik { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<obavijest> obavijest { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<upis> upis { get; set; }
        public virtual grupa grupa { get; set; }
    }
}
