//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KindergartenJoy
{
    using System;
    using System.Collections.Generic;
    
    public partial class obavijest
    {
        public int obavijest_id { get; set; }
        public int korisnik_id { get; set; }
        public string naslov { get; set; }
        public System.DateTime datum_vrijeme { get; set; }
        public string opis { get; set; }
        public System.DateTime datum_dogadaja { get; set; }
    
        public virtual korisnik korisnik { get; set; }
    }
}
