//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ObavijestiService
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Entities : DbContext
    {
        public Entities()
            : base("name=Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<aktivnost> aktivnost { get; set; }
        public virtual DbSet<biljeska> biljeska { get; set; }
        public virtual DbSet<dijete> dijete { get; set; }
        public virtual DbSet<dnevnik> dnevnik { get; set; }
        public virtual DbSet<evidencija> evidencija { get; set; }
        public virtual DbSet<grupa> grupa { get; set; }
        public virtual DbSet<korisnik> korisnik { get; set; }
        public virtual DbSet<obavijest> obavijest { get; set; }
        public virtual DbSet<radi_u> radi_u { get; set; }
        public virtual DbSet<se_nalazi> se_nalazi { get; set; }
        public virtual DbSet<tip_korisnik> tip_korisnik { get; set; }
        public virtual DbSet<tip_radnja> tip_radnja { get; set; }
        public virtual DbSet<upis> upis { get; set; }
    }
}
